### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by plagelao** [plagelao/walkingthepath#2]
**In order to** personalice de user experience

**As a** developer of walkingthepath

**I want to** know who is using the app

**Comment by plagelao** [comment]
Sign out!

**Comment by jmbeas** [comment]
The current solution, using OAuth works fine deployed in heroku but in localhost the link in the homepage is pointing to http://localhost:3000/auth/twitter and gives the error "OAuth::Unauthorized 401 Unauthorized"

**Comment by plagelao** [comment]
You're right. I can't make it work in local. You have to do some work :P

Every app that uses Twitter for authentication needs to be registered in [Twitter apps](https://dev.twitter.com/apps/new). Once the app is registered, Twitter gives you 2 keys (Consumer key and Consumer secret). I can not commit those keys :P so, if you want your app to work in local, you need to register a new app and use the new keys in [config/initializers/omniauth.rb](https://github.com/plagelao/walkingthepath/blob/master/config/initializers/omniauth.rb) instead of the 2 env variables (I need those for heroku)

I'll write more about it in the readme soon :(
